---
- name: Deploy inventory app to kind
  hosts: ec2
  become: yes

  vars:
    k8s_dir: "/home/ubuntu/k8s-inventory"

  tasks:
    - name: Create folder for manifests
      file:
        path: "{{ k8s_dir }}"
        state: directory

    - name: Copy namespace manifest
      copy:
        src: "infra/k8s/namespace.yml"
        dest: "{{ k8s_dir }}/namespace.yml"

    - name: Copy deployment manifest
      copy:
        src: "infra/k8s/deployment.yml"
        dest: "{{ k8s_dir }}/deployment.yml"

    - name: Copy service manifest
      copy:
        src: "infra/k8s/service.yml"
        dest: "{{ k8s_dir }}/service.yml"

    - name: Apply namespace
      command: kubectl apply -f {{ k8s_dir }}/namespace.yml

    - name: Apply deployment
      command: kubectl apply -f {{ k8s_dir }}/deployment.yml

    - name: Apply service
      command: kubectl apply -f {{ k8s_dir }}/service.yml
