---
- name: Deploy inventory app to kind
  hosts: all
  become: true

  tasks:
    - name: Create folder for manifests
      file:
        path: /home/ubuntu/k8s-inventory
        state: directory

    - name: Copy Kubernetes manifests
      copy:
        src: "{{ item }}"
        dest: "/home/ubuntu/k8s-inventory/{{ item | basename }}"
      loop:
        - infra/k8s/namespace.yml
        - infra/k8s/deployment.yml
        - infra/k8s/service.yml

    - name: Apply namespace
      shell: kubectl apply -f /home/ubuntu/k8s-inventory/namespace.yml

    - name: Apply deployment
      shell: kubectl apply -f /home/ubuntu/k8s-inventory/deployment.yml

    - name: Apply service
      shell: kubectl apply -f /home/ubuntu/k8s-inventory/service.yml
