- name: Deploy inventory app to kind
  hosts: all
  become: true

  vars:
    k8s_dir: /home/ubuntu/k8s-inventory

  tasks:
    - name: Create folder for manifests on EC2
      file:
        path: "{{ k8s_dir }}"
        state: directory

    - name: Copy Kubernetes manifests to EC2
      copy:
        src: "{{ playbook_dir }}/k8s/{{ item }}"
        dest: "{{ k8s_dir }}/{{ item }}"
      loop:
        - namespace.yml
        - deployment.yml
        - service.yml

    - name: Apply namespace
      shell: kubectl apply -f {{ k8s_dir }}/namespace.yml

    - name: Apply deployment
      shell: kubectl apply -f {{ k8s_dir }}/deployment.yml

    - name: Apply service
      shell: kubectl apply -f {{ k8s_dir }}/service.yml
